spring:
  redis:
    host: localhost
    port: 6379
custom:
  jwt:
    access: qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM
    refresh: qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM
file:
  upload-dir: test_data
