/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/member/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description username, password, nickname, email 정보를 입력하여 회원가입을 진행합니다.
         */
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 파일 업로드
         * @description PDF 파일을 업로드합니다. 로그인한 사용자만 가능하며 MultipartFile 형식을 사용합니다.
         */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reIssue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description RefreshToken 을 이용해 AccessToken 을 재발급합니다.
         */
        post: operations["reIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 아이디와 비밀번호를 입력하여 로그인 후 AccessToken 을 반환합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PDF 페이지 대본을 기반으로 음성 합성 요청
         * @description 업로드된 PDF에서 생성한 페이지별 대본(script)을 FastAPI로 전달하여
         *     각 페이지의 음성을 합성하고, 생성된 음성 파일명을 반환합니다.
         *
         *     - 요청 Body에는 pdfId와 페이지별 대본 리스트(pdfInfo)가 포함됩니다.
         *     - FastAPI는 모든 페이지를 한 번에 처리하며, 각 페이지마다 음성 파일이 생성됩니다.
         *     - 응답으로는 pageNum, script, audioFileName이 포함된 리스트가 반환됩니다.
         */
        post: operations["speech"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PDF 스크립트 생성
         * @description PDF ID와 파일명을 받아 PDF에서 대본을 생성합니다.
         */
        post: operations["script"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 업로드된 파일 리스트 조회
         * @description 로그인한 사용자가 업로드한 PDF 목록을 반환합니다.
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JoinRequest: {
            username?: string;
            password?: string;
            nickname?: string;
            email?: string;
        };
        ApiResponseMember: {
            success?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["Member"];
        };
        FileDocument: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            modifyDate?: string;
            member?: components["schemas"]["Member"];
            originalName?: string;
            storedName?: string;
            filePath?: string;
            scripts?: components["schemas"]["Script"][];
        };
        Member: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            modifyDate?: string;
            username?: string;
            password?: string;
            nickname?: string;
            email?: string;
            role?: string;
            fileDocuments?: components["schemas"]["FileDocument"][];
        };
        Script: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            createDate?: string;
            /** Format: date-time */
            modifyDate?: string;
            /** Format: int32 */
            pageNum?: number;
            script?: string;
            audioPath?: string;
            fileDocument?: components["schemas"]["FileDocument"];
        };
        ApiResponseFileDto: {
            success?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["FileDto"];
        };
        FileDto: {
            /** Format: int64 */
            pdfId?: number;
            originalName?: string;
            storedName?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            code?: string;
            message?: string;
            data?: Record<string, never>;
        };
        LoginRequest: {
            username?: string;
            password?: string;
        };
        ApiResponseObject: {
            success?: boolean;
            code?: string;
            message?: string;
            data?: Record<string, never>;
        };
        PdfInfo: {
            /** Format: int32 */
            pageNum?: number;
            script?: string;
        };
        ScriptDto: {
            /** Format: int64 */
            pdfId?: number;
            pdfInfos?: components["schemas"]["PdfInfo"][];
        };
        ApiResponseSpeechDto: {
            success?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["SpeechDto"];
        };
        SpeechDto: Record<string, never>;
        ScriptRequest: {
            /** Format: int64 */
            pdfId?: number;
            pdfName?: string;
        };
        ApiResponseScriptDto: {
            success?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["ScriptDto"];
        };
        ApiResponseListFileDto: {
            success?: boolean;
            code?: string;
            message?: string;
            data?: components["schemas"]["FileDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMember"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFileDto"];
                };
            };
        };
    };
    reIssue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseObject"];
                };
            };
        };
    };
    speech: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSpeechDto"];
                };
            };
        };
    };
    script: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseScriptDto"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListFileDto"];
                };
            };
        };
    };
}
